name: ayanda
owner: georgemathenge
package: .
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    - path: /
      headers:
      - name: Accept
        value: text/html
      - name: Accept-Language
        value: en-US
    max_age: 59m
  database:
    engine: mysql
volumes:
- name: uploads_data
  mount: /app/wp-content/uploads
- name: plugins_data
  mount: /app/wp-content/plugins
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
