name: ayanda
owner: georgemathenge
package: .
capabilities:

  database:
    engine: mysql
volumes:
- name: uploads_data
  mount: /app/wp-content/uploads
- name: plugins_data
  mount: /app/wp-content/plugins
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
